version: '3'

services:

  nginx:
    image: nginx:1.17.10
    container_name: dsp_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/certs:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - dspfront
      - dspback

  dspfront:
    image: dspfront
    container_name: dspfront
    build:
      context: ./dspfront
      dockerfile: Dockerfile
    depends_on:
      - dspback
    ports:
      - 5001:5001
    restart: on-failure
    volumes:
      - ./dspfront:/dspfront
      - /dspfront/node_modules

  dspback:
    image: dspback
    container_name: dspback
    volumes:
      - ./dspback:/dspback
    build:
      context: ./dspback
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 5002:5002
    restart: on-failure

  database:
    image: postgres:13.1
    container_name: database
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
