services:
    dspfront:
        image: dspfront:latest
        container_name: dspfront
        volumes:
            - ./dspfront/.env:/dspfront/.env
        depends_on:
            - dspback
        ports:
            - 5001:5001
        environment:
            - VITE_APP_HEAP_ANALYTICS_APP_ID=${VITE_APP_HEAP_ANALYTICS_APP_ID}
            - VITE_APP_GOOGLE_MAPS_API_KEY=${VITE_APP_GOOGLE_MAPS_API_KEY}
            - VITE_APP_DISCOVERY_PORTAL_URL=${VITE_APP_DISCOVERY_PORTAL_URL}
            - VITE_APP_API_URL=${VITE_APP_API_URL}
            - VITE_APP_URL=${VITE_APP_URL}
        restart: unless-stopped

    dspback:
        image: dspback:latest
        container_name: dspback
        volumes:
            - ./dspback/.env:/dspback/.env
        ports:
            - 5002:5002
        restart: unless-stopped
