version: '3'

services:

  nginx:
    image: nginx:1.17.10
    container_name: dsp_nginx
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - dspback

  dspback:
    image: dspback
    container_name: dspback
    volumes:
      - ./.env:/dspback/.env
    build:
      context: ./dspback
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - 5002:5002
    restart: on-failure

  database:
    image: postgres:13.1
    container_name: database
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: "${DATABASE_USERNAME}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"

    volumes:
      - ./db-data/:/var/lib/postgresql/data/
