version: '3'

services:

  nginx:
    image: nginx:1.17.10
    container_name: dsp_nginx
    volumes:
      - ./nginx/nginx-dev.conf:/etc/nginx/nginx.conf
      - ./nginx/config:/etc/ssl
    ports:
      - 443:443
    depends_on:
      - dspback

  dspback:
    image: dspback
    container_name: dspback
    volumes:
      - ./.env:/dspback/.env
      - ./dspback:/dspback
    entrypoint: bash dev-entrypoint.sh
    build:
      context: ./dspback
      dockerfile: Dockerfile-dev
    depends_on:
      - mongodb
    ports:
      - 5002:5002
    restart: on-failure

  mongodb:
    image: mongo:5.0
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=AzureDiamond
      - MONGO_INITDB_ROOT_PASSWORD=hunter2
