version: '3.8'

services:

  dspfront:
    image: dspfront
    container_name: dspfront
    build:
      context: ./dspfront
      dockerfile: Dockerfile
    depends_on:
      - dspback
    ports:
      - 5001:5001
    environment:
      - VUE_APP_HEAP_ANALYTICS_APP_ID=${VUE_APP_HEAP_ANALYTICS_APP_ID}
      - VUE_APP_GOOGLE_MAPS_API_KEY=${VUE_APP_GOOGLE_MAPS_API_KEY}
      - VUE_APP_DISCOVERY_PORTAL_URL=${VUE_APP_DISCOVERY_PORTAL_URL}
      - VUE_APP_API_URL=${VUE_APP_API_URL}
      - VUE_APP_URL=${VUE_APP_URL}
    restart: unless-stopped

  dspback:
    image: dspback
    container_name: dspback
    build:
      context: ./dspback
      dockerfile: Dockerfile
    ports:
      - 5002:5002
    restart: unless-stopped
